name: Vérification de Fusion de PR

on:
  pull_request:
    types: [closed]

jobs:
  check_merge:
    runs-on: ubuntu-latest
    if: ${{github.event.pull_request.merged == true}}
    steps:
      - name: Afficher message si fusionnée
        run: echo "La PR a été mergée"